-- ALTER TABLE USER
-- MODIFY Email VARCHAR(64) UNIQUE NOT NULL;

-- ALTER TABLE GROUP_MEMBER
-- MODIFY Role ENUM('Admin','Moderator','Member','Guest') NOT NULL;

-- ALTER TABLE USER
-- DROP COLUMN Phone;