DROP VIEW DEPARTMENT_STAFF;

CREATE VIEW DEPARTMENT_STAFF
(DName,SName,Job)
AS (
    SELECT DEPARTMENT.Name, STAFF.Name, STAFF.Job
    FROM DEPARTMENT JOIN STAFF ON (DEPARTMENT.Manager = STAFF.Supervisor)
    UNION
    SELECT DEPARTMENT.Name, STAFF.Name, STAFF.Job
    FROM DEPARTMENT JOIN STAFF ON (DEPARTMENT.Manager = STAFF.StaffId)
);