SELECT DISTINCT Label, REGION.Name, COUNT(StreamId) AS N
FROM 
    (MOVIE JOIN REGION)
    LEFT JOIN 
    (STREAM NATURAL JOIN CUSTOMER
            JOIN COUNTRY ON (CUSTOMER.Country = COUNTRY.Name)) USING (MovieId,RegionId)
    NATURAL JOIN MOVIE_GENRE
    JOIN GENRE USING (GenreId)
GROUP BY Label, REGION.Name
ORDER BY Label;