SELECT CUSTOMER.Name, MAX(STREAM.Charge)
FROM STREAM JOIN CUSTOMER ON (STREAM.CustomerId = CUSTOMER.CustomerId)
WHERE Country = 'United States' AND YEAR(StreamDate) = 2018
GROUP BY CUSTOMER.Name
ORDER BY MAX(STREAM.Charge) DESC, CUSTOMER.Name;