SELECT Title, COUNT(*) AS N
FROM MOVIE JOIN STREAM USING (MovieId)
     JOIN CUSTOMER USING (CustomerId)
     JOIN COUNTRY ON (Country = COUNTRY.Name)
     JOIN REGION USING (RegionId)
WHERE REGION.Name = 'Asia'
GROUP BY Title
ORDER BY N DESC, Title
LIMIT 20;