SELECT A1.Name, A2.Name, COUNT(DISTINCT(MovieId)) AS M, COUNT(StreamId) AS N
FROM (ACTOR A1 NATURAL JOIN MOVIE_ACTOR MA1) JOIN
     (ACTOR A2 NATURAL JOIN MOVIE_ACTOR MA2) USING (MovieId)
      NATURAL JOIN MOVIE LEFT JOIN STREAM USING (MovieId)
WHERE
    A1.Name < A2.Name AND MA1.MovieId = MA2.MovieId
GROUP BY A1.Name, A2.Name
HAVING N >= 40
ORDER BY N DESC, M DESC, A1.Name, A2.Name;